nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        # 'https://api-adresse.data.gouv.fr/':
        #     allow_origin: ['*']
        #     allow_headers: ['X-Custom-Auth']
        #     allow_methods: ['GET']
        #     max_age: 3600
        # 'https://unpkg.com/':
        #     allow_origin: ['*']
        #     allow_headers: ['X-Custom-Auth']
        #     allow_methods: ['GET']
        #     max_age: 3600
        '^/': null
