version: '3'
 
services:
  # database:
    # image: postgres:${POSTGRES_VERSION:-15}-alpine
    # environment:
    #   POSTGRES_DB: ${POSTGRES_VERSION:-organize}
    #   # You should definitely change the password in production
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    #   POSTGRES_USER: ${POSTGRES_USER:-app}
    # volumes:
    #   - database_data:/var/lib/postgresql/data:rw
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: organize
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database_data: